import React from 'react';
import { Container } from 'react-bootstrap';

class GeneralConditions extends React.Component {
    render() {
        return (
            <div>
                <Container>
                    <div style={{paddingTop:"80px", paddingBottom:"80px"}}>
                        <h1 className="text-center p-5">DÉCLARATION DE CONFIDENTIALITÉ</h1>
                        <p>Watch Market Club accorde une grande importance à vos données personnelles. La Déclaration de Confidentialité a pour but de vous informer sur le traitement des données personnelles que nous collectons lors de votre accès à nos services en ligne et hors ligne.</p>
                        <p>La Cookie Policy de WMC vient compléter la présente Déclaration de Confidentialité et décrit ce qu’est un cookie, l’usage qui peut en être fait par WMC et les moyens permettant à toute personne d’accepter ou de refuser le dépôt sur son terminal d’un cookie opéré par WMC. Vous pouvez accéder à notre Cookie Policy ici.</p>
                        <p>Lorsque vous fournissez vos données personnelles à Watch Market Club, celle-ci est responsable de la collecte et du traitement de vos données personnelles, au niveau local, à des fins de gestion de la relation commerciale ou de la relation contractuelle relative aux produits et services Watch Market Club, conformément aux lois locales qui lui sont applicables. </p>
                        <p>Conformément au Règlement Général sur la Protection des Données n° 2016/679 adopté au sein de l’Union Européenne (« RGPD ») et à la Loi fédérale du 19 juin 1992 sur la protection des données, telle que modifiée le 25 septembre 2020 (« LPD »), la Déclaration de Confidentialité est régie et interprétée par le RGPD et la LPD, sous le contrôle du Préposé fédéral à la protection des données et à la transparence, dans la mesure où la société Watch Market Club est responsable.</p>
                        <p>Toutefois, Watch Market Club peut tenir compte de dispositions plus strictes que le RGPD ou la LPD, lorsque la loi l’exige.</p>
                        <h2 className="text-center p-5">1. DONNÉES PERSONNELLES QUE NOUS RECUEILLONS</h2>
                        <p>La Déclaration de Confidentialité s’applique aux données personnelles que nous sommes susceptibles de recueillir auprès de vous ou à votre sujet (voir ci-dessous), à partir des sources suivantes :</p>
                        <p>• Visite de notre site web Watchmarketclub.com, la réponse à un formulaire ou l’utilisation d’un service, abonnement à notre newsletter, demande de contact, d’informations ou de services, prise de rendez-vous. Vous serez invité à vous identifier mais vous pouvez aussi visiter notre Site sans vous enregistrer;</p>
                        <p>• Communications électroniques et téléphoniques, ainsi que des échanges en présentiel, même informels, entre Watch Market Club et vous-même ;</p>
                        <p>• Achat d’un produit Watch Market Club ou demande d’un service après-vente ;</p>
                        <p>• Communications électroniques et téléphoniques avec les centres relations clients Watch Market Club ;</p>
                        <p>• Données que vous partagez publiquement dans le cadre de votre interaction avec Watch Market Club sur des réseaux sociaux (par exemple, lorsque vous « aimez » une page Watch Market Club sur les réseaux sociaux, tels que Facebook, Instagram, Linkedin, Twitter, Pinterest, Wechat, Weibo, Line, Youtube and Yuku).</p>
                        <p>Nous sommes susceptibles de recueillir différents types d’informations auprès de vous en fonction de la finalité et de la manière dont vous interagissez avec Watch Market Club (en présentiel, en ligne, par téléphone, etc.), comme cela est indiqué ci-dessous :</p>
                        <p>• Identité et coordonnées : il s’agit de toute information que vous nous fournissez et qui nous permettrait de vous contacter, tel que votre nom, votre adresse électronique, votre adresse postale ou votre numéro de téléphone, ainsi que votre image, telle que vous l’avez éventuellement téléchargée sur votre compte personnel.</p>
                        <p>• Statut personnel, préférences et historique d’achats: toute information décrivant vos caractéristiques démographiques et comportementales. Il s’agit, par exemple de votre date de naissance, votre sexe, votre nationalité, votre préférence linguistique, votre situation professionnelle (titre professionnel, société/employeur, coordonnées professionnelles), votre situation matrimoniale, vos centres d’intérêts (sports, loisirs, art) ou votre style de vie, ainsi que d’autres préférences, tels que vos produits préférés, votre liste de favoris, les montres enregistrées dans votre compte et l’historique de vos achats et des services que vous avez demandés.</p>
                        <p>• Données relatives au trafic et à l’utilisation de notre Site : lorsque vous interagissez avec notre Site, nous sommes susceptibles de collecter des données relatives au trafic au moyen de technologies de collecte de données automatisées, impliquant notamment un dialogue entre le serveur du site web et votre navigateur. Les données relatives au trafic peuvent inclure le nom du navigateur et le type d'appareil que vous utilisez, ainsi que des données techniques relatives à votre mode de connexion à notre Site, notamment votre système d'exploitation, l’adresse IP de votre terminal connecté à Internet, l’identifiant de votre point d’accès à Internet, la date et l’heure de votre dernière visite et les fournisseurs d'accès Internet auxquels vous faites appel. Ces données sont utilisées à des fins statistiques et leur analyse nous sert à améliorer notre Site, pour vous offrir une expérience de navigation personnalisée adaptée à vos préférences et à vos centres d’intérêts, par exemple en affichant directement les pages dans votre langue préférée lors de votre prochaine visite. Ces informations sont saisies au moyen de technologies automatisées comme les cookies (les cookies du navigateur) et les balises Web (tel que Java Script) ; elles sont également recueillies par le biais de services de suivi externes (Google Analytics). Vous pouvez consulter notre Cookie Policy pour savoir de quelle façon vous pouvez régler vos paramètres concernant les cookies et pour obtenir des informations détaillées sur les cookies que nous utilisons et l’usage que nous en faisons.</p>
                        <p>• Commentaires des clients : il s’agit des informations que vous partagez volontairement avec nous au sujet de votre expérience d’utilisation de nos produits et de nos services (par exemple, en cas de réclamation ou dans le cadre de discussions, même informelles, avec nos collaborateurs).</p>
                        <p>• Informations provenant d’un réseau social : nous pouvons avoir accès à des informations que vous partagez publiquement sur des réseaux sociaux tiers, tels que les réseaux sociaux cités plus haut. Si vous souhaitez cesser de partager lesdites informations, nous vous recommandons de consulter les conditions d’utilisation du réseau social concerné.</p>
                        <p>Liens vers d'autres sites web. Notre Site peut contenir ou utiliser des liens renvoyant vers des sites web de tiers (notamment publicitaires, partenaires ou réseau social). Ces sites web de tiers possèdent leur propre politique de confidentialité (notamment sur l'usage de cookies), que nous vous invitons à examiner. Nous n'acceptons aucune responsabilité à l'égard des politiques de confidentialité de tels sites web tiers et auxquels vous accédez à vos propres risques.</p>
                        <p>Vie privée et protection des mineurs. Notre Site ne s’adressent pas aux utilisateurs de moins de 16 ans. Nous ne recueillons pas sciemment des données personnelles d’enfants de moins de 16 ans. Si vous êtes un parent ou un tuteur et que vous savez que votre enfant nous a fourni des données personnelles, veuillez nous contacter. Si nous réalisons ou sommes informés que nous avons recueilli des données personnelles d’un enfant de moins de 16 ans sans vérification du consentement parental, nous prendrons des mesures pour supprimer ces informations de nos serveurs. Dans tous les cas, les utilisateurs de moins de 16 ans qui nous auraient fourni des données personnelles disposent d’un droit discrétionnaire à l’effacement de leurs données qu’ils peuvent exercer, à tout moment et sans motif, seul ou par le biais de leur tuteur habituel, en nous contactant à l’adresse mentionnée au chapitre VIII « Nous contacter ». Les demandes d’effacement seront traitées dans les conditions et sous les réserves décrites ci-dessus.</p>
                        <h2 className="text-center p-5">2. UTILISATION DE VOS DONNÉES PERSONNELLES</h2>
                        <p>Nous recueillons et utilisons vos données personnelles en nous fondant sur une ou plusieurs des bases juridiques suivantes :</p>
                        <p>• Nous avons obtenu votre consentement préalable (par exemple lorsque vous vous abonnez à notre bulletin d’information). Veuillez noter qu’avec cette base juridique particulière, vous avez le droit de révoquer votre consentement à tout moment.</p>
                        <p>• Nous avons un intérêt légitime pour effectuer le traitement et cet intérêt légitime n’est pas éclipsé par vos intérêts, droits fondamentaux ou libertés (par exemple la prévention contre toute activité frauduleuse ou illégale) ;</p>
                        <p>• Nous devons traiter vos données personnelles afin de respecter les lois et la réglementation en vigueur. Selon le contexte, nous pouvons utiliser vos données personnelles pour les finalités décrites ci-dessous. Veuillez noter que les types d’utilisation figurant ci-dessous dépendent de l’utilisation que vous faites de nos services et ne concernent pas systématiquement chaque utilisateur :</p>
                        <p>• Répondre à vos requêtes, questions et/ou demandes en tous genres, notamment vos demandes d’exercice de droits ;</p>
                        <p>• Améliorer le service client, personnaliser et gérer notre relation avec vous. Les données collectées, qui peuvent être recoupées à partir des différentes sources, nous aident à répondre à vos demandes, à satisfaire plus efficacement vos besoins et à améliorer nos produits et nos services en fonction de vos préférences.</p>
                        <p>• Vous envoyer régulièrement des informations, notamment sur Watch Market Club, les nouveautés de nos produits ou services après-vente.</p>
                        <p>• Respecter nos obligations en termes de facturation et de comptabilité, ainsi que nos obligations légales et réglementaires (telles que celles résultant de la législation en matière de lutte contre le blanchiment d’argent et de la législation sur les embargos) ;</p>
                        <p>• Garantir la sécurité informatique et des opérations informatiques.</p>
                        <h2 className="text-center p-5">3. COMMENT NOUS PROTÉGEONS VOS DONNÉES PERSONNELLES</h2>
                        <p>Nous avons mis en place des mesures organisationnelles, humaines et techniques pour protéger de façon adéquate vos données personnelles, ainsi que les traitements que nous faisons de celles-ci. Les mesures appliquées, afin d’éviter tout accès non autorisé à vos données personnelles et leur altération, divulgation ou destruction, suivent des standards reconnus en matière de sécurité de l’information. Ces mesures de sécurité consistent principalement en un contrôle strict des accès, un chiffrement des données personnelles inscrites dans nos bases de données clients et clients potentiels, une revue régulière des accès, un maintien de l’infrastructure à un niveau de protection adéquat, une supervision constante de celle-ci, ainsi qu’une stratégie d’analyse et de remédiation des potentiels incidents de sécurité.</p>
                        <p>Néanmoins, même si nous nous efforçons de protéger vos données personnelles en notre possession, nous ne pouvons pas garantir la sécurité des informations transmises sur notre Site lors de leur transit via Internet au moyen d’un protocole non sécurisé.</p>
                        <h2 className="text-center p-5">4. PARTAGE DE VOS DONNÉES PERSONNELLES</h2>
                        <p>Nous nous engageons à ne pas vendre, échanger, louer ou transférer d'une quelconque manière vos données personnelles sans votre consentement (qui aura été donné après réception d’une information préalable).</p>
                        <p>Lorsque nous transférons des données personnelles vers un pays qui n’est pas désigné par le Préposé fédéral à la protection des données et à la transparence ou par la Commission Européenne comme assurant un niveau suffisant de protection des données personnelles, les transferts sont régis par les clauses contractuelles en vigueur adoptées par la Commission Européenne et reprises par le Préposé ou au travers de mécanismes validés par ces derniers ou par les autorités compétentes en charge de la protection des données personnelles au sein de l’Espace Économique Européen et, le cas échéant, complétées par des mesures qui pourraient être exigées dans d’autres juridictions.</p>
                        <p>• Nous pouvons partager vos demandes de contact ou de prise de rendez-vous avec les détaillants ou les centres de réparation concernés ;</p>
                        <p>• Nous pourrons communiquer ces données à une entité tierce dans le cadre d'une fusion ou d'un rachat, ou encore à toute organisation impliquée dans un transfert ou une vente de notre activité ou de notre capital.</p>
                        <p>Nous exigeons toujours de ces tiers qu'ils présentent des garanties de confidentialité et de sécurité suffisantes et qu’ils prennent les mesures organisationnelles et techniques nécessaires pour protéger vos données personnelles conformément à la législation applicable. Lorsque nous transférons des données personnelles vers un pays qui n’est pas désigné par le Préposé fédéral à la protection des données et à la transparence ou par la Commission Européenne comme assurant un niveau suffisant de protection des données personnelles, les transferts sont régis par les clauses contractuelles en vigueur adoptées par la Commission Européenne et reprises par le Préposé ou au travers de mécanismes validés par ces derniers ou par les autorités compétentes en charge de la protection des données personnelles au sein de l’Espace Économique Européen et, le cas échéant, complétées par des mesures qui pourraient être exigées dans d’autres juridictions. Par ailleurs, les prestataires de services ne sont autorisés à accéder à vos données personnelles et à les utiliser pour notre compte qu’eu égard aux tâches spécifiques qui leur ont été assignées, sur la base de nos instructions.</p>
                        <p>La liste des pays dans lesquels nous transférons des données personnelles peut évoluer. Vous pouvez demander une liste à jour des pays dans lesquels nous sommes susceptibles de transférer vos données personnelles pour des finalités déterminées à l’adresse indiquée au chapitre VIII « nous contacter ».</p>
                        <p>Transfert à des tiers pour des motifs juridiques : nous sommes susceptibles de communiquer des données personnelles pour satisfaire des exigences légales, répondre à la demande d’un organisme compétent chargé de l’application de la loi, exercer nos droits ou nous défendre dans le cadre d'une réclamation ou d’une procédure judiciaire ou pour fournir une preuve, pour protéger les intérêts d'une entité Audemars Piguet et lutter contre la fraude.</p>
                        <h2 className="text-center p-5">5. CONSERVATION DE VOS DONNÉES PERSONNELLES</h2>
                        <p>Nous conservons vos données personnelles pendant le délai nécessaire à la satisfaction des différentes finalités définies au chapitre II ci-dessus, sauf dans les cas où la loi nous autorise ou exige de les conserver plus longtemps.</p>
                        <p>En particulier :</p>
                        <p>• Les données personnelles utilisées pour gérer notre relation avec vous ou pour vous envoyer des informations, notamment sur les services après-vente,  des enquêtes de satisfaction seront conservées pour la durée nécessaire à la gestion de notre relation avec vous, et au maximum pour une durée de trois ans à compter de la fin de votre relation commerciale avec Watch Market Club ou de votre dernière utilisation des services disponibles sur notre Site ou de votre dernier contact avec Watch Market Club si vous êtes rattaché à un pays de l’Espace Economique Européen ou à la Suisse. Ce délai est étendu à dix ans si vous êtes rattaché aux Etats-Unis et à cinq ans si vous êtes rattaché à un autre pays.</p>
                        <p>• Les données liées à la gestion et à l’historique des services fournis, ainsi qu’à la gestion des réclamations et des appels à garantie seront conservées pour une durée maximale de dix ans à compter du dernier événement. </p>
                        <p>• Les données personnelles traitées pour la gestion des demandes d’accès et de rectification des données personnelles seront conservées pour une durée maximale de trois ans.</p>
                        <p>Ces durées maximales s’appliquent sauf si vous demandez l’effacement ou la cessation d’utilisation de vos données avant l’expiration de ces durées pour un motif compatible avec une obligation légale de conservation qui s'impose à Watch Market Club.</p>
                        <h2 className="text-center p-5">6. VOS DROITS SUR VOS DONNÉES PERSONNELLES</h2>
                        <p>loi applicable le prévoit, vous pouvez  demander à accéder aux données personnelles vous concernant détenues par Watch Market Club, les consulter et en obtenir une copie papier ou électronique, et demander la correction, la limitation, la mise à jour ou la suppression de vos données personnelles ou vous opposer à leur traitement. Vous pouvez exercer ces droits en adressant une demande écrite, accompagnée d’une copie de votre pièce d’identité, à Watch Market Club avec qui vous interagissez ou à l'adresse postale ou électronique indiquées au chapitre VIII « Nous contacter » ci-dessous. Nous nous efforcerons de vous présenter les données personnelles concernées, de les corriger ou de les effacer, en fonction de votre demande et dans les conditions prévues par la loi applicable.</p>
                        <p>Il est par ailleurs possible que nous devions conserver certaines de vos données personnelles après votre demande de suppression, afin de respecter nos obligations légales ou contractuelles. Nous pouvons également être autorisés par la loi applicable à conserver certaines de vos données personnelles pour répondre à nos obligations légales.</p>
                        <p>Opt-out : vous pouvez également à tout moment demander à ne plus recevoir d’informations ou d’offres de notre part, soit en suivant le processus de désinscription décrit dans les messages que vous recevrez de notre part, soit en nous écrivant à l’adresse indiquée au chapitre VIII « Nous contacter » ci-dessous. Si vous le faites, nous mettrons rapidement à jour notre base de données et prendrons toutes les mesures raisonnables pour répondre à votre demande le plus rapidement possible, mais nous pouvons continuer à vous contacter dans la mesure nécessaire en lien avec tout produit ou service que vous avez demandé.</p>
                        <p>Réclamation auprès d’une autorité de contrôle : sans préjudice de toute autre voie de droit, vous avez notamment le droit d’introduire une réclamation auprès de l’autorité de contrôle de l’Union Européenne compétente pour l’application des règles du RGPD ou auprès de l’autorité compétente aux conditions prévues par la LPD.</p>
                        <h2 className="text-center p-5">7. MODIFICATIONS DE NOTRE DÉCLARATION DE CONFIDENTIALITÉ</h2>
                        <p>Nous nous réservons le droit de modifier la Déclaration de Confidentialité à tout moment. Nous vous encourageons à consulter régulièrement cette page pour prendre connaissance des modifications et rester informé sur les mesures que nous prenons pour protéger les données personnelles que nous recueillons. Vous acceptez et reconnaissez qu’il vous incombe de consulter régulièrement nos Sites pour prendre connaissance des modifications qui lui sont apportées.</p>
                        <h2 className="text-center p-5">8. NOUS CONTACTER</h2>
                        <p>Pour toute question relative à cette Déclaration de Confidentialité, veuillez nous contacter à l'adresse e-mail <a href="mailto:info@watchmarketclub.com">info@watchmarketclub.com</a> ou à l’adresse postale Watch Market Club 40 rue Laugier 75017 Paris</p>
                        <p className='p-5'>Ce document a été mis à jour le  19 Octobre 2021</p>
                    </div>
                </Container>
            </div>
        );
    }
}

export default GeneralConditions;